# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 00:12
from __future__ import unicode_literals

import account.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='driving_experience',
            field=models.IntegerField(null=True, validators=[account.validator.validate_experience], verbose_name='опыт работы'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[account.validator.validate_name], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[account.validator.validate_name], verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='middle_name',
            field=models.CharField(max_length=30, validators=[account.validator.validate_name], verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.CharField(blank=True, max_length=30, validators=[account.validator.validate_profession], verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profession',
            field=models.CharField(blank=True, max_length=30, validators=[account.validator.validate_profession], verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='professional_experience',
            field=models.PositiveSmallIntegerField(null=True, validators=[account.validator.validate_experience], verbose_name='опыт работы'),
        ),
    ]
