# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160307_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='professional_experience',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
