# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160307_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isExpert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='isModerator',
            field=models.BooleanField(default=False),
        ),
    ]
