# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160307_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='isExpert',
            new_name='is_expert',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='isModerator',
            new_name='is_moderator',
        ),
    ]
