# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:46
from __future__ import unicode_literals

import assessment.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20160307_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveSmallIntegerField(validators=[assessment.validator.validate_point])),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Quality'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set([('quality', 'expert')]),
        ),
    ]
