# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='category',
            field=models.CharField(choices=[('VS', 'Свойства зрительного анализаторов'), ('HR', 'Свойства слухового анализатора'), ('SM', 'Свойства обонятельного анализатора'), ('TM', 'Свойства температурного анализатора'), ('TC', 'Свойства тактильного анализатора'), ('AT', 'Свойства внимания'), ('MM', 'Свойства памяти'), ('TN', 'Свойства мышления'), ('RT', 'Сенсомоторные реакции'), ('VM', 'Свойства зрительного, двигательного, вестибулярного, слухового анализаторов'), ('VH', 'Свойства зрительного, слухового, кожного, двигательного анализаторов'), ('AI', 'Свойства интеллекта'), ('VV', 'Свойства зрительного и вестибулярного анализаторов'), ('HN', 'Свойства высшей нервной деятельности'), ('EM', 'Свойства эмоционально-волевой и мотивационной сфер')], max_length=60, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='quality',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
