# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20160527_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
